---
title: "stemi_olink_peakckmb"
output: html_document
date: "2022-12-21"
---

```{r header, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
#!/usr/bin/env Rscript
############################################################################################################################
# Authors: Roy Oelen, Irene van Blokland
# Name: stemi_olink_peakckmb.Rmd
# Function: link the expression of olink proteins to the peak ck mb values
############################################################################################################################
```

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# libraries        #
####################

```

```{r functions, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# Functions        #
####################

## Loading formulas
olink_to_plottable_table <- function(olink, split_char='\\.'){
  id_and_timepoint_df <- NULL
  # check the rownames
  for(id_and_timepoint in rownames(olink)){
    # split into id and timepoint
    id_and_timepoint_split <- strsplit(id_and_timepoint, split_char)
    id <- id_and_timepoint_split[[1]][[1]]
    timepoint <- id_and_timepoint_split[[1]][[2]]
    # turn into row
    id_and_timepoint_row <- data.frame(id=c(id), timepoint=c(timepoint))
    # add to dataframe
    if(is.null(id_and_timepoint_df)){
      id_and_timepoint_df <- id_and_timepoint_row
    }
    else{
      id_and_timepoint_df <- rbind(id_and_timepoint_df, id_and_timepoint_row)
    }
  }
  # add new columns to original data
  olink <- cbind(id_and_timepoint_df, olink)
  return(olink)
}


# calculating peak CK-MB values of every participant
add_peak_ck_mb <- function(clinvar_object){
  # subset to the ckmb variables
  ckmb <- clinvar[, grep('ck_mb', colnames(clinvar_object))]
  # change the NA variables to -1
  ckmb[is.na(ckmb)] <- -1
  # get the maximum
  max_ckmb <- apply(ckmb, 1, max)
  # replace a -1 with NA, this means there was no real variable
  max_ckmb[max_ckmb == -1] <- NA
  # paste onto the existing object
  clinvar_object$peak_ck_mb <- max_ckmb
  return(clinvar_object)
}


perform_simple_linear_model <- function(protein_data, clinvar_data, clinvar_columns=c('peak_ck_mb', 'age', 'sex'), mtc_methods=c('BH', 'bonferroni'), timepoint_column='timepoint', timepoints=c('Baseline', 't24h', 't8w'), id_column="id", clinvar_id_column="record_id", clinvar_prepend='TEST_', protein_start_column_nr=3){
  # put the results in a table
  result_table <- NULL
  # for convenience sake, we will turn the timepoint columns into strings
  protein_data[[timepoint_column]] <- as.character(protein_data[[timepoint_column]])
  # if we are using a prepend
  clinvar_data[[clinvar_id_column]] <- paste(clinvar_prepend, clinvar_data[[clinvar_id_column]], sep = '')
  # we will check each timepoint
  for(timepoint in intersect(timepoints, unique(protein_data[[timepoint_column]]))){
    # subset the protein data to this timepoint
    protein_data_timepoint <- protein_data[protein_data[[timepoint_column]] == timepoint, ]
    # paste each clinical variable onto it
    protein_data_timepoint[, clinvar_columns] <- clinvar_data[match(protein_data_timepoint[[id_column]], clinvar_data[[clinvar_id_column]]), clinvar_columns]
    # check each protein, the last columns are the clinical variables we pasted onto the dataframe, so we'll skip those columns, they are not protein data
    for(protein in colnames(protein_data_timepoint)[protein_start_column_nr:(ncol(protein_data_timepoint) - length(clinvar_columns))]){
      # grab the data of the clinical variables and the protein
      protein_data_timepoint_protein <- protein_data_timepoint[, c(protein, clinvar_columns)]
      # we'll rename the protein to be 'protein', this makes grabbing the results a bit simpler
      colnames(protein_data_timepoint_protein)[[1]] <- 'protein'
      # we want only the complete entries, and get these by summing the NAs in each row, if there are no NAs, the sum is zero
      protein_data_timepoint_protein <- protein_data_timepoint_protein[apply(protein_data_timepoint_protein, 1, FUN = function(x){
        return(sum(is.na(x)))
      }) == 0, ]
      # we'll build the formula now
      formula_explanatory_variables <- paste(clinvar_columns, collapse = '+')
      formula_string <- paste('protein', '~', formula_explanatory_variables)
      formula <- formula(formula_string)
      # these values we will extract
      variables_per_clinical_variable <- c('p', 'estimate', 'se', 't')
      # make combinations of these variables for each clinical variable
      clinvar_variable_result_columns_df <- expand.grid(clinvar_columns, variables_per_clinical_variable) # creates dataframe of each combination as two columns
      clinvar_variable_result_columns <- paste(clinvar_variable_result_columns_df[[1]], clinvar_variable_result_columns_df[[2]], sep = '.') # turn the rows into the combinations we want
      # let's get all thos columns together then
      result_columns <- c('protein', 'timepoint', 'n', 'r2', 'adj_r2', clinvar_variable_result_columns)
      # create a empty result first
      result_row <- data.frame(matrix(NA, nrow=1, ncol=length(result_columns), dimnames = list(NULL, result_columns)))
      # fill in what we already know
      result_row[1, 'protein'] <- protein
      result_row[1, 'timepoint'] <- timepoint
      result_row[1, 'n'] <- nrow(protein_data_timepoint_protein)
      # we will try to do linear regression now. This might fail, but we then want to give an NA result, not exit
      try({
        linear_regression <- summary(lm(formula = formula, data = protein_data_timepoint_protein))
        # extract the shared variables
        r2 = as.numeric(linear_regression$r.squared)
        adj_r2 = as.numeric(linear_regression$adj.r.squared)
        # add to the result
        result_row[1, 'r2'] <- r2
        result_row[1, 'adj_r2'] <- adj_r2
        # check of each clinical variable the results
        for(clinvar_column in clinvar_columns){
          # get all these variables
          p = as.numeric(linear_regression$coefficients[[clinvar_column, 'Pr(>|t|)']])
          estimate = as.numeric(linear_regression$coefficients[[clinvar_column, 'Estimate']])
          se = as.numeric(linear_regression$coefficients[[clinvar_column, 'Std. Error']])
          t = as.numeric(linear_regression$coefficients[[clinvar_column, 't value']])
          # set these as variables
          result_row[1, paste(clinvar_column, 'p', sep='.')] <- p
          result_row[1, paste(clinvar_column, 'estimate', sep ='.')] <- estimate
          result_row[1, paste(clinvar_column, 'se', sep = '.')] <- se
          result_row[1, paste(clinvar_column, 't', sep = '.')] <- t
        }
      })
      # let's add this result
      if(is.null(result_table)){
        result_table <- result_row
      }
      else{
        result_table <- rbind(result_table, result_row)
      }
    }
  }
  # do MTC if requested
  for(method in mtc_methods){
    # for each p we have
    for(clinvar in clinvar_columns){
      # paste the original column name together
      orig_column <- paste(clinvar, 'p', sep = '.')
      # and the new column
      new_column <- paste(clinvar, method, sep = '.')
      # do the actual calculation
      result_table[[new_column]] <- p.adjust(result_table[[orig_column]], method = method)
    }
  }
  return(result_table)
}


calc_age_in_days <- function(date_of_birth_string, split_character='/', day_of_month_col=1, month_of_year_col=2, year_col=3){
  # split the string
  split_string <- strsplit(date_of_birth_string, split = split_character)[[1]]
  day = as.numeric(split_string[day_of_month_col])
  month = as.numeric(split_string[month_of_year_col])
  year = as.numeric(split_string[year_col])
  # create new string as input for the Date library
  standard_data_string <- paste(day, month, year, sep = '/')
  # turn into date object
  birth <- as.Date(standard_data_string, format='%d/%m/%Y')
  # get now
  now_string <- Sys.Date()
  # convert to Date as well
  now <- as.Date(now_string, format='%Y-%m-%d')
  # get the time between now and the birth
  age_days <- difftime(now, birth, units = 'days')
  return(age_days)
}


perform_simple_linear_model_protein <- function(protein_data, clinvar_data, clinvar_column='peak_ck_mb', clinvar_covars=c('age', 'sex'), mtc_methods=c('BH', 'bonferroni'), timepoint_column='timepoint', timepoints=c('Baseline', 't24h', 't8w'), id_column="id", clinvar_id_column="record_id", clinvar_prepend='TEST_', protein_start_column_nr=3){
  # put the results in a table
  result_table <- NULL
  # for convenience sake, we will turn the timepoint columns into strings
  protein_data[[timepoint_column]] <- as.character(protein_data[[timepoint_column]])
  # if we are using a prepend
  clinvar_data[[clinvar_id_column]] <- paste(clinvar_prepend, clinvar_data[[clinvar_id_column]], sep = '')
  # combine the interested variable with the covariates
  clinvar_columns <- c(clinvar_column, clinvar_covars)
  # we will check each timepoint
  for(timepoint in intersect(timepoints, unique(protein_data[[timepoint_column]]))){
    # subset the protein data to this timepoint
    protein_data_timepoint <- protein_data[protein_data[[timepoint_column]] == timepoint, ]
    # paste each clinical variable onto it
    protein_data_timepoint[, clinvar_columns] <- clinvar_data[match(protein_data_timepoint[[id_column]], clinvar_data[[clinvar_id_column]]), clinvar_columns]
    # check each protein, the last columns are the clinical variables we pasted onto the dataframe, so we'll skip those columns, they are not protein data
    for(protein in colnames(protein_data_timepoint)[protein_start_column_nr:(ncol(protein_data_timepoint) - length(clinvar_columns))]){
      # grab the data of the clinical variables and the protein
      protein_data_timepoint_protein <- protein_data_timepoint[, c(protein, clinvar_columns)]
      # we'll rename the protein to be 'protein', this makes grabbing the results a bit simpler
      colnames(protein_data_timepoint_protein)[[1]] <- 'protein'
      # we want only the complete entries, and get these by summing the NAs in each row, if there are no NAs, the sum is zero
      protein_data_timepoint_protein <- protein_data_timepoint_protein[apply(protein_data_timepoint_protein, 1, FUN = function(x){
        return(sum(is.na(x)))
      }) == 0, ]
      # we'll build the formula now
      formula_string <- paste(clinvar_column, '~', 'protein')
      # if we have covariates, we will add these as well
      if(length(clinvar_covars) > 0 ){
        formula_explanatory_variables <- paste(clinvar_covars, collapse = '+')
        formula_string <- paste(formula_string, '+', formula_explanatory_variables, sep = '')
      }
      formula <- formula(formula_string)
      # these values we will extract
      variables_per_clinical_variable <- c('p', 'estimate', 'se', 't')
      # make combinations of these variables for each covariate, and the protein
      clinvar_variable_result_columns_df <- expand.grid(c('protein', clinvar_covars), variables_per_clinical_variable) # creates dataframe of each combination as two columns
      clinvar_variable_result_columns <- paste(clinvar_variable_result_columns_df[[1]], clinvar_variable_result_columns_df[[2]], sep = '.') # turn the rows into the combinations we want
      # let's get all thos columns together then
      result_columns <- c('protein', 'timepoint', 'n', 'r2', 'adj_r2', clinvar_variable_result_columns)
      # create a empty result first
      result_row <- data.frame(matrix(NA, nrow=1, ncol=length(result_columns), dimnames = list(NULL, result_columns)))
      # fill in what we already know
      result_row[1, 'protein'] <- protein
      result_row[1, 'timepoint'] <- timepoint
      result_row[1, 'n'] <- nrow(protein_data_timepoint_protein)
      # we will try to do linear regression now. This might fail, but we then want to give an NA result, not exit
      try({
        linear_regression <- summary(lm(formula = formula, data = protein_data_timepoint_protein))
        # extract the shared variables
        r2 = as.numeric(linear_regression$r.squared)
        adj_r2 = as.numeric(linear_regression$adj.r.squared)
        # add to the result
        result_row[1, 'r2'] <- r2
        result_row[1, 'adj_r2'] <- adj_r2
        # check of each covariate, and the protein
        for(variate in c('protein', clinvar_covars)){
          # get all these variables
          p = as.numeric(linear_regression$coefficients[[variate, 'Pr(>|t|)']])
          estimate = as.numeric(linear_regression$coefficients[[variate, 'Estimate']])
          se = as.numeric(linear_regression$coefficients[[variate, 'Std. Error']])
          t = as.numeric(linear_regression$coefficients[[variate, 't value']])
          # set these as variables
          result_row[1, paste(variate, 'p', sep='.')] <- p
          result_row[1, paste(variate, 'estimate', sep ='.')] <- estimate
          result_row[1, paste(variate, 'se', sep = '.')] <- se
          result_row[1, paste(variate, 't', sep = '.')] <- t
        }
      })
      # let's add this result
      if(is.null(result_table)){
        result_table <- result_row
      }
      else{
        result_table <- rbind(result_table, result_row)
      }
    }
  }
  # do MTC if requested
  for(method in mtc_methods){
    # for each p we have
    for(variate in c('protein', clinvar_covars)){
      # paste the original column name together
      orig_column <- paste(variate, 'p', sep = '.')
      # and the new column
      new_column <- paste(variate, method, sep = '.')
      # do the actual calculation
      result_table[[new_column]] <- p.adjust(result_table[[orig_column]], method = method)
    }
  }
  # add the dependent variable for clearness sake
  result_table$dependant <- clinvar_column
  return(result_table)
}


```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
####################
# Main Code        #
####################

# location of various files
olinkid_to_uid_loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/protein_data/olink/olinkid_to_uniprotid.tsv'
uniprotid_to_gs_loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/protein_data/olink/uniprot_to_genesymbol.tsv'
gs_to_ens_loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/protein_data/features_v3.tsv'
olink_loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/protein_data/olink/20200442_Groot_NPX-QC_format_fixed.tsv'
inclusion_list_loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/metadata/included_participants.txt'
metadata_loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/metadata//cardio.integrated.20210301.metadata.tsv'
clinvar_loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/clinical_parameters/scRNAseq_clinical_data_20200910_final_notextfields.tsv'

# load mapping files
gs_to_ens <- read.table(gs_to_ens_loc, sep = '\t', header = F)
uniprotid_to_gs <- read.table(uniprotid_to_gs_loc, sep = '\t', header = T)
olinkid_to_uid <- read.table(olinkid_to_uid_loc, sep = '\t', header = T)
# and read the actual data
olink <- read.table(olink_loc, sep = '\t', header = T, row.names = 1)
# covert so that the timepoint is split as a separate column
olink_plottable <- olink_to_plottable_table(olink)
# get the participants to include
inclusion_list <- read.table(inclusion_list_loc, header = F)$V1
# subset to the ones we want to include
olink_plottable <- olink_plottable[!is.na(olink_plottable[['id']]) & olink_plottable[['id']] %in% inclusion_list, ]

# read the clinvar table
clinvar <- read.table(clinvar_loc, header = T, sep = '\t', dec = ',', stringsAsFactors = F)
# calculate the peak ck_mb
clinvar <- add_peak_ck_mb(clinvar)
# add log of peak and baseline ckmb
clinvar$log_peak_ck_mb <- log(clinvar$peak_ck_mb)
clinvar$log_ck_mb <- log(clinvar$ck_mb)

# add the age
clinvar$age <- apply(clinvar, 1, function(x){
  age <- calc_age_in_days(as.character(x[['date_birth']]), split_character =  '/', year_col = 3, month_of_year_col = 2, day_of_month_col = 1)
  return(age)
})

```

```{r regression, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# We first copy the olink data and put it in a metadata file
metadata <- olink_plottable[, c('id', 'timepoint')]
# Then we only take the protein data from the metadata
protein_data_log <- olink_plottable[, setdiff(colnames(olink_plottable), c('id', 'timepoint'))]
# And we log transform the proteins
protein_data_log <- log(protein_data_log)
# Add the log transformed proteins to the protein data together with the metadata
protein_data_log <- cbind(metadata, protein_data_log)
# try to explain protein by peak_ck_mb
log_protein_by_peakckmb <- perform_simple_linear_model(protein_data = protein_data_log, clinvar_data = clinvar, clinvar_prepend='TEST_', clinvar_columns = c('peak_ck_mb'))
# make the protein more clear
log_protein_by_peakckmb[['protein']] <- olinkid_to_uid[match(log_protein_by_peakckmb[['protein']], olinkid_to_uid[['OlinkID']]), 'Assay']
```

```{r regression_result, include=TRUE}
knitr::opts_chunk$set(echo = FALSE)

print(
  log_protein_by_peakckmb[order(log_protein_by_peakckmb[['peak_ck_mb.p']]), ]
)

```

```{r regression_reverse, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# explain peak_ck_mb by protein+age+gender
peak_ck_mb_by_protein <- perform_simple_linear_model_protein(protein_data = olink_plottable, clinvar_data = clinvar, clinvar_column='peak_ck_mb', clinvar_covars=c('age', 'gender'), clinvar_prepend='TEST_')
# explain log peak_ck_mb by protein+log_ck_mb+gender+age
log_peak_ck_mb_by_protein <- perform_simple_linear_model_protein(protein_data = olink_plottable, clinvar_data = clinvar, clinvar_column='log_peak_ck_mb', clinvar_covars=c('age', 'gender'), clinvar_prepend='TEST_')
# explain peak_ck_mb by log_protein+age+gender
peak_ck_mb_by_log_protein <- perform_simple_linear_model_protein(protein_data = protein_data_log, clinvar_data = clinvar, clinvar_column='peak_ck_mb', clinvar_covars=c('age', 'gender'), clinvar_prepend='TEST_')

# make the protein more clear
log_peak_ck_mb_by_protein[['protein']] <- olinkid_to_uid[match(log_peak_ck_mb_by_protein[['protein']], olinkid_to_uid[['OlinkID']]), 'Assay']

```

```{r regression_reverse, include=TRUE}
knitr::opts_chunk$set(echo = FALSE)

print(
  log_peak_ck_mb_by_protein[order(log_peak_ck_mb_by_protein[['protein.p']]), ]
)

```
