---
title: "stemi_gse_enrichr"
author: "Roy Oelen"
date: "2023-01-11"
output: html_document
---

```{r header, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
#!/usr/bin/env Rscript
############################################################################################################################
# Authors: Roy Oelen
# Name: stemi_gse_enrichr.Rmd
# Function: perform gene set enrichment with REACTOME and enrichr
############################################################################################################################
```

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# libraries        #
####################

# for doing the enrichment
library(enrichR)
# for parallel processing
library(foreach)

```

```{r functions, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# Functions        #
####################


#' get each gene and their LFC from a MAST output file created using the Seurat version of MAST
#' 
#' @param mast.output.loc the location of the output file
#' @param p.val.column the column to use for filtering the significant genes
#' @param p.val.cutoff the cutoff value to use for filtering the significant genes
#' @returns a table with the DE genes filtered by the given significance level
#' 
get_gene_and_lfc_seurat_mast <- function(mast.output.loc, p.val.column='p_val_adj', p.val.cutoff=0.05){
  # read the output
  de.output <- read.table(mast.output.loc, header = T, row.names = 1, sep = '\t', stringsAsFactors = F)
  # subset to what is significant
  de.output.significant <- de.output[de.output[[p.val.column]] < p.val.cutoff, ]
  return(de.output.significant)
}


#' get each gene and their LFC from a limma output file
#' 
#' @param limma.output.loc the location of the output file
#' @param p.val.column the column to use for filtering the significant genes
#' @param p.val.cutoff the cutoff value to use for filtering the significant genes
#' @returns a table with the DE genes filtered by the given significance level
#' 
get_gene_and_lfc_limma <- function(limma.output.loc, p.val.column='adj.P.Val', p.val.cutoff=0.05){
  # read the output
  de.output <- read.table(limma.output.loc, header = T, row.names = 1, sep = '\t', stringsAsFactors = F)
  # subset to what is significant
  de.output.significant <- de.output[!is.na(de.output[[p.val.column]]) & de.output[[p.val.column]] < p.val.cutoff, ]
  return(de.output.significant)
}


#' get each gene and their LFC from a MAST output file created using the standalone version of MAST
#' 
#' @param mast.output.loc the location of the output file
#' @param p.val.column the column to use for filtering the significant genes
#' @param p.val.cutoff the cutoff value to use for filtering the significant genes
#' @param contrast the value in the model that we are interested in
#' @returns a table with the DE genes filtered by the given significance level
#' 
get_gene_and_lfc_standalone_mast <- function(mast.output.loc, p.val.column='bonferroni', p.val.cutoff=0.05, contrast='inflammation_statusNI'){
  # read the output
  de.output <- read.table(mast.output.loc, header = T, sep = '\t', stringsAsFactors = F)
  # subset to just the contrast we care about
  de.output.contrast <- de.output[de.output[['contrast']] == contrast &
                                    de.output[['component']] == 'H', ]
  # subset to just what is significant
  de.output.contrast.significant <- de.output.contrast[!is.na(de.output.contrast[[p.val.column]]) & de.output.contrast[[p.val.column]] < p.val.cutoff, ]
  # we can now safely set the rownames to be the genes, as with one contrast, there is only one entry per gene
  rownames(de.output.contrast.significant) <- de.output.contrast.significant[['primerid']]
  return(de.output.contrast.significant)
}


#' get each gene and their LFC from a DE output file
#' 
#' @param de.output.loc the location of the output file
#' @param de_method the methods used to generate the output file (mast_standalone, mast_seurat, limma)
#' @param p.val.column the column to use for filtering the significant genes
#' @param p.val.cutoff the cutoff value to use for filtering the significant genes
#' @param contrast the value in the model that we are interested in (only necessary for mast_standalone)
#' @returns a table with the DE genes filtered by the given significance level
#' 
get_de_output <- function(de.output.loc, de_method, p.val.column='bonferroni', p.val.cutoff=0.05, contrast='inflammation_statusNI'){
  # use the correct method
  de.output <- NULL
  if (de_method == 'mast_standalone') {
    de.output <- get_gene_and_lfc_standalone_mast(de.output.loc, p.val.column = p.val.column, p.val.cutoff = p.val.cutoff, contrast = contrast)
  }
  else if (de_method == 'mast_seurat') {
    de.output <- get_gene_and_lfc_seurat_mast(de.output.loc, p.val.column = p.val.column, p.val.cutoff = p.val.cutoff)
  }
  else if (de_method == 'limma'){
    de.output <- get_gene_and_lfc_limma(de.output.loc, p.val.column = p.val.column, p.val.cutoff = p.val.cutoff)
  }
  else{
    print('de_method not valid, valid options are: mast_standalone, mast_seurat, limma')
  }
  return(de.output)
}


#' use enrichr to do gene set enrichment on each DE output file in a directory
#' 
#' @param mast.output.loc the folder containing the DE output files
#' @param pathway.output.loc the folder to place the GSE results
#' @param de_method the methods used to generate the output file (mast_standalone, mast_seurat, limma)
#' @param p.val.column the column to use for filtering the significant genes
#' @param p.val.cutoff the cutoff value to use for filtering the significant genes
#' @param log.fc.column the column containing the log fold change of the gene
#' @param abs_lfc_cutoff the cutoff for the lfc where to include the genes
#' @param contrast.var the value in the model that we are interested in (only necessary for mast_standalone)
#' @param list.regex regular expression pattern to use when lising the DE output files
#' @param do_positive test just the positive LFC genes
#' @param do_negative test just the negative LFC genes
#' @param do_joint test genes regardless of LFC direction
#' @returns 0 if succesfull
#' do_enrichr(limma_lowm20_output_path, gse_enrichr_limma_lowm20_output_path, de_method = 'limma', log.fc.column = 'logFC', p.val.column = 'p.bonferroni')
do_enrichr <- function(mast.output.loc, pathway.output.loc, de_method='mast_seurat', log.fc.column='avg_log2FC', p.val.column='p_val_adj', p.val.cutoff=0.05, abs_lfc_cutoff=0, contrast.var = NULL, list.regex = NULL, do_positive=T, do_negative=T, do_joint=T, database='Reactome_2016'){
  # check if the output folder exists
  if(!dir.exists(pathway.output.loc)){
    dir.create(pathway.output.loc, recursive = T)
  }
  # get the DE output files
  mast.output.files <- list.files(mast.output.loc, full.names = T, pattern = list.regex)
  # check each cell type
  for(mast.output.file in mast.output.files){
    #foreach(mast.output.file=mast.output.files) %do% {
    # get the basename
    mast.output.file.basename <- basename(mast.output.file)
    # I was not consistent naming
    comparison <- NULL
    if (de_method == 'limma') {
      comparison <- sub(pattern = "(.*)\\..*$", replacement = "\\1",x = mast.output.file.basename)
    }
    else{
      # get the comparison from that
      comparison <- sub(pattern = "(.*?)\\..*$", replacement = "\\1", x = mast.output.file.basename)
    }
    # get the full path to the DE file
    de.output.loc <- mast.output.file
    # read the output
    #de.output <- read.table(de.output.loc, header = T, row.names = 1, sep = '\t', stringsAsFactors = F)
    # get only the significant result
    #de.output <- de.output[de.output[[p.val.column]] < p.val.cutoff, ]
    de.output <- get_de_output(de.output.loc = de.output.loc, de_method = de_method, p.val.column = p.val.column, p.val.cutoff = p.val.cutoff, contrast = contrast.var)
    # check if there are any results
    if(nrow(de.output) > 0){
      # do absolute log fold change cutoff
      if (!is.null(abs_lfc_cutoff) & abs_lfc_cutoff > 0) {
        de.output <- de.output[abs(de.output[[log.fc.column]]) > abs_lfc_cutoff, ]
      }
      # do lfc cutoff as well
      if (do_joint==T) {
        # grab the genes
        gene.symbols.sig <- rownames(de.output)
        try({
          # do the enrichment analysis
          enriched <- enrichr(genes = gene.symbols.sig, databases = c(database))
          # grab the reactome result
          enriched.reactome <- enriched[[database]]
          # write a result if there is one
          if(nrow(enriched.reactome) > 0){
            # paste the output path together
            enriched.reactome.loc <- paste(pathway.output.loc, comparison, '.tsv', sep = '')
            # write the result
            write.table(enriched.reactome, enriched.reactome.loc, sep = '\t', quote = T, row.names = F, col.names = T)
            Sys.sleep(5)
          }
        })
      }
      # now check for the negative genes
      de.output.negative <- de.output[de.output[[log.fc.column]] < 0, ]
      # check if there are any genes left
      if(nrow(de.output.negative) > 0 & do_negative==T){
        try({
          # grab the genes
          gene.symbols.sig.negative <- rownames(de.output.negative)
          # do the enrichment analysis
          enriched.negative <- enrichr(genes = gene.symbols.sig.negative, databases = c(database))
          # grab the reactome result
          enriched.reactome.negative <- enriched.negative[[database]]
          # write a result if there is one
          if(nrow(enriched.reactome.negative) > 0){
            # paste the output path together
            enriched.reactome.negative.loc <- paste(pathway.output.loc, comparison, '_negative', '.tsv', sep = '')
            # write the result
            write.table(enriched.reactome.negative, enriched.reactome.negative.loc, sep = '\t', quote = T, row.names = F, col.names = T)
            Sys.sleep(5)
          }
        })
      }
      # now check for the positive genes
      de.output.positive <- de.output[de.output[[log.fc.column]] > 0, ]
      # check if there are any genes left
      if(nrow(de.output.positive) > 0 & do_positive==T){
        try({
          # grab the genes
          gene.symbols.sig.positive <- rownames(de.output.positive)
          # do the enrichment analysis
          enriched.positive <- enrichr(genes = gene.symbols.sig.positive, databases = c(database))
          # grab the reactome result
          enriched.reactome.positive <- enriched.positive[[database]]
          # write a result if there is one
          if(nrow(enriched.reactome.positive) > 0){
            # paste the output path together
            enriched.reactome.positive.loc <- paste(pathway.output.loc, comparison, '_positive', '.tsv', sep = '')
            # write the result
            write.table(enriched.reactome.positive, enriched.reactome.positive.loc, sep = '\t', quote = T, row.names = F, col.names = T)
            Sys.sleep(5)
          }
        })
      }
    }
    else{
      print(paste('no genes significant for', mast.output.file))
    }
  }
  return(0)
}


```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# Main Code        #
####################

setEnrichrSite("Enrichr") # Human genes

# location of the Seurat MAST output
mast.output.meta.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/differential_expression/MAST/stemi_meta_paired_lores_lfc01minpct01ncountrna_20210301/rna/'
# location of the GSE output
gse.output.meta.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/pathway_enrichment/enrichr/MAST/stemi_meta_paired_lores_lfc01minpct01ncountrna_20210301/rna/'
# do the GSE
do_enrichr(mast.output.meta.loc, gse.output.meta.loc, p.val.column = 'metap_bonferroni', log.fc.column = 'metafc')


# for v2 as well
mast.output.v2.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/differential_expression/MAST/stemi_v2_paired_lores_lfc01minpct01ncountrna_20210301/rna/'
gse.output.v2.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/pathway_enrichment/enrichr/MAST/stemi_v2_paired_lores_lfc01minpct01ncountrna_20210301/rna/'
do_enrichr(mast.output.v2.loc, gse.output.v2.loc)

# and v3
mast.output.v3.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/differential_expression/MAST/stemi_v3_paired_lores_lfc01minpct01ncountrna_20210301/rna/'
gse.output.v3.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/pathway_enrichment/enrichr/MAST/stemi_v3_paired_lores_lfc01minpct01ncountrna_20210301/rna/'
do_enrichr(mast.output.v3.loc, gse.output.v3.loc)

# location of limma output
limma.output.loc <-  '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/differential_expression/limma_dream/stemi_both_paired_lores_lfc01minpct01ncountrna_20210301/sct/chem_assignment_age_gender/'
# location of limma gse output
gse.output.limma.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/pathway_enrichment/enrichr/limma_dream/stemi_both_paired_lores_lfc01minpct01ncountrna_20210301/sct/chem_assignment_age_gender/'
# do gse
do_enrichr(limma.output.loc, gse.output.limma.loc, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = T, do_negative = F, do_joint = F, list.regex = '*.tsv')
do_enrichr(limma.output.loc, gse.output.limma.loc, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = F, do_negative = T, do_joint = F, list.regex = '*.tsv')
do_enrichr(limma.output.loc, gse.output.limma.loc, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = F, do_negative = F, do_joint = T, list.regex = '*.tsv')

# location of limma output
limma.meta.output.loc <-  '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/differential_expression/limma_dream/stemi_meta_paired_lores_lfc01minpct01ncountrna_20210301/sct/chem_assignment_age_gender/'
# location of limma gse output
gse.output.limma.meta.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/pathway_enrichment/enrichr/limma_dream/stemi_meta_paired_lores_lfc01minpct01ncountrna_20210301/sct/chem_assignment_age_gender/'
# do gse
do_enrichr(limma.meta.output.loc, gse.output.limma.meta.loc, p.val.column = 'invnorm.TestStatistic.signed', log.fc.column = 'meta_fc', de_method = 'limma', do_positive = T, do_negative = F, do_joint = F, list.regex = '*.tsv')
do_enrichr(limma.meta.output.loc, gse.output.limma.meta.loc, p.val.column = 'invnorm.TestStatistic.signed', log.fc.column = 'meta_fc', de_method = 'limma', do_positive = F, do_negative = T, do_joint = F, list.regex = '*.tsv')
do_enrichr(limma.meta.output.loc, gse.output.limma.meta.loc, p.val.column = 'invnorm.TestStatistic.signed', log.fc.column = 'meta_fc', de_method = 'limma', do_positive = F, do_negative = F, do_joint = T, list.regex = '*.tsv')

```

```{r signed_mast, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# location of the Seurat MAST output
mast.output.signed.meta.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/differential_expression/MAST/stemi_metasamesign_paired_lores_lfc01minpct01ncountrna_20210301_wstats_byncell/rna/'
# location of the GSE output
gse.output.signed.meta.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/pathway_enrichment/enrichr/MAST/stemi_metasamesign_paired_lores_lfc01minpct01ncountrna_20210301_wstats_byncell/rna/'
# do the GSE
do_enrichr(mast.output.signed.meta.loc, gse.output.signed.meta.loc, p.val.column = 'invnorm.pval.bonferroni', log.fc.column = 'meta_fc', do_positive = T, do_negative = F, do_joint = F)
do_enrichr(mast.output.signed.meta.loc, gse.output.signed.meta.loc, p.val.column = 'invnorm.pval.bonferroni', log.fc.column = 'meta_fc', do_positive = F, do_negative = T, do_joint = F)
do_enrichr(mast.output.signed.meta.loc, gse.output.signed.meta.loc, p.val.column = 'invnorm.pval.bonferroni', log.fc.column = 'meta_fc', do_positive = F, do_negative = F, do_joint = T)

```

```{r signed_mast_kegg, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

gse.output.limma.loc.kegg <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/pathway_enrichment/enrichr_kegg/limma_dream/stemi_both_paired_lores_lfc01minpct01ncountrna_20210301/sct/chem_assignment_age_gender/'
do_enrichr(limma.output.loc, gse.output.limma.loc.kegg, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = T, do_negative = F, do_joint = F, list.regex = '*.tsv', database = 'KEGG_2021_Human')
do_enrichr(limma.output.loc, gse.output.limma.loc.kegg, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = F, do_negative = T, do_joint = F, list.regex = '*.tsv', database = 'KEGG_2021_Human')
do_enrichr(limma.output.loc, gse.output.limma.loc.kegg, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = F, do_negative = F, do_joint = T, list.regex = '*.tsv', database = 'KEGG_2021_Human')

```

```{r limma_reactome_new, include=FALSE}

# location of limma output
limma.output.loc <-  '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/differential_expression/limma_dream/stemi_both_paired_lores_lfc01minpct01ncountrna_20210301/sct/chem_assignment_age_gender/'
# location of limma gse output
gse.output.limma.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/pathway_enrichment/enrichr_reactome_2023/limma_dream/stemi_both_paired_lores_lfc01minpct01ncountrna_20210301/sct/chem_assignment_age_gender/'
# do gse
do_enrichr(limma.output.loc, gse.output.limma.loc, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = T, do_negative = F, do_joint = F, database = 'Reactome_2022', list.regex = '*.tsv')
do_enrichr(limma.output.loc, gse.output.limma.loc, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = F, do_negative = T, do_joint = F, database = 'Reactome_2022',  list.regex = '*.tsv')
do_enrichr(limma.output.loc, gse.output.limma.loc, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = F, do_negative = F, do_joint = T, database = 'Reactome_2022',  list.regex = '*.tsv')

```

```{r limma_reactome_new_05, include=FALSE}

# location of limma output
limma.output.loc <-  '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/differential_expression/limma_dream/stemi_both_paired_lores_lfc01minpct01ncountrna_20210301/sct/chem_assignment_age_gender/'
# location of limma gse output
gse.output.limma.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/pathway_enrichment/enrichr_reactome_2023_lfc05/limma_dream/stemi_both_paired_lores_lfc01minpct01ncountrna_20210301/sct/chem_assignment_age_gender/'
# do gse
do_enrichr(limma.output.loc, gse.output.limma.loc, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = T, do_negative = F, do_joint = F, database = 'Reactome_2022', list.regex = '*.tsv', abs_lfc_cutoff = 0.5)
do_enrichr(limma.output.loc, gse.output.limma.loc, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = F, do_negative = T, do_joint = F, database = 'Reactome_2022',  list.regex = '*.tsv', abs_lfc_cutoff = 0.5)
do_enrichr(limma.output.loc, gse.output.limma.loc, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = F, do_negative = F, do_joint = T, database = 'Reactome_2022',  list.regex = '*.tsv', abs_lfc_cutoff = 0.5)

```

```{r limma_reactome_new_01, include=FALSE}

# location of limma output
limma.output.loc <-  '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/differential_expression/limma_dream/stemi_both_paired_lores_lfc01minpct01ncountrna_20210301/sct/chem_assignment_age_gender/'
# location of limma gse output
gse.output.limma.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/pathway_enrichment/enrichr_reactome_2023_lfc01/limma_dream/stemi_both_paired_lores_lfc01minpct01ncountrna_20210301/sct/chem_assignment_age_gender/'
# do gse
do_enrichr(limma.output.loc, gse.output.limma.loc, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = T, do_negative = F, do_joint = F, database = 'Reactome_2022', list.regex = '*.tsv', abs_lfc_cutoff = 0.1)
do_enrichr(limma.output.loc, gse.output.limma.loc, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = F, do_negative = T, do_joint = F, database = 'Reactome_2022',  list.regex = '*.tsv', abs_lfc_cutoff = 0.1)
do_enrichr(limma.output.loc, gse.output.limma.loc, p.val.column = 'p.bonferroni', log.fc.column = 'logFC', de_method = 'limma', do_positive = F, do_negative = F, do_joint = T, database = 'Reactome_2022',  list.regex = '*.tsv', abs_lfc_cutoff = 0.1)

```