---
title: "stemi_gse_enrichr"
author: "Roy Oelen"
date: "2023-01-11"
output: html_document
---

```{r header, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
#!/usr/bin/env Rscript
############################################################################################################################
# Authors: Roy Oelen
# Name: stemi_gse_enrichr.Rmd
# Function: perform gene set enrichment with REACTOME and enrichr
############################################################################################################################
```

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# libraries        #
####################

# for doing the enrichment
library(enrichR)
# for parallel processing
library(foreach)

```

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# Functions        #
####################


get_gene_and_lfc_seurat_mast <- function(mast.output.loc, p.val.column='p_val_adj', p.val.cutoff=0.05){
  # read the output
  de.output <- read.table(mast.output.loc, header = T, row.names = 1, sep = '\t', stringsAsFactors = F)
  # subset to what is significant
  de.output.significant <- de.output[de.output[[p.val.column]] < p.val.cutoff, ]
  return(de.output.significant)
}


get_gene_and_lfc_limma <- function(limma.output.loc, p.val.column='adj.P.Val', p.val.cutoff=0.05){
  # read the output
  de.output <- read.table(limma.output.loc, header = T, row.names = 1, sep = '\t', stringsAsFactors = F)
  # subset to what is significant
  de.output.significant <- de.output[de.output[[p.val.column]] < p.val.cutoff, ]
  return(de.output.significant)
}


get_gene_and_lfc_standalone_mast <- function(mast.output.loc, p.val.column='bonferroni', p.val.cutoff=0.05, contrast='inflammation_statusNI'){
  # read the output
  de.output <- read.table(mast.output.loc, header = T, sep = '\t', stringsAsFactors = F)
  # subset to just the contrast we care about
  de.output.contrast <- de.output[de.output[['contrast']] == contrast &
                                    de.output[['component']] == 'H', ]
  # subset to just what is significant
  de.output.contrast.significant <- de.output.contrast[de.output.contrast[[p.val.column]] < p.val.cutoff, ]
  # we can now safely set the rownames to be the genes, as with one contrast, there is only one entry per gene
  rownames(de.output.contrast.significant) <- de.output.contrast.significant[['primerid']]
  return(de.output.contrast.significant)
}


get_de_output <- function(de.output.loc, de_method, p.val.column='bonferroni', p.val.cutoff=0.05, contrast='inflammation_statusNI'){
  # use the correct method
  de.output <- NULL
  if (de_method == 'mast_standalone') {
    de.output <- get_gene_and_lfc_standalone_mast(de.output.loc, p.val.column = p.val.column, p.val.cutoff = p.val.cutoff, contrast = contrast)
  }
  else if (de_method == 'mast_seurat') {
    de.output <- get_gene_and_lfc_seurat_mast(de.output.loc, p.val.column = p.val.column, p.val.cutoff = p.val.cutoff)
  }
  else if (de_method == 'limma'){
    de.output <- get_gene_and_lfc_limma(de.output.loc, p.val.column = p.val.column, p.val.cutoff = p.val.cutoff)
  }
  else{
    print('de_method not valid, valid options are: mast_standalone, mast_seurat, limma')
  }
  return(de.output)
}



do_enrichr <- function(mast.output.loc, pathway.output.loc, de_method='mast_seurat', log.fc.column='avg_log2FC', p.val.column='p_val_adj', p.val.cutoff=0.05, contrast.var = NULL, list.regex = NULL){
  # check if the output folder exists
  if(!dir.exists(pathway.output.loc)){
    dir.create(pathway.output.loc, recursive = T)
  }
  # get the DE output files
  mast.output.files <- list.files(mast.output.loc, full.names = T, pattern = list.regex)
  # check each cell type
  #for(mast.output.file in mast.output.files){
  foreach(mast.output.file=mast.output.files) %do% {
    # get the basename
    mast.output.file.basename <- basename(mast.output.file)
    # get the comparison from that
    comparison <- sub(pattern = "(.*?)\\..*$", replacement = "\\1", x = mast.output.file.basename)
    # get the full path to the DE file
    de.output.loc <- mast.output.file
    # read the output
    #de.output <- read.table(de.output.loc, header = T, row.names = 1, sep = '\t', stringsAsFactors = F)
    # get only the significant result
    #de.output <- de.output[de.output[[p.val.column]] < p.val.cutoff, ]
    de.output <- get_de_output(de.output.loc = de.output.loc, de_method = de_method, p.val.column = p.val.column, p.val.cutoff = p.val.cutoff, contrast = contrast.var)
    # check if there are any results
    if(nrow(de.output) > 0){
      # grab the genes
      gene.symbols.sig <- rownames(de.output)
      # do the enrichment analysis
      enriched <- enrichr(genes = gene.symbols.sig, databases = c('Reactome_2016'))
      # grab the reactome result
      enriched.reactome <- enriched[['Reactome_2016']]
      # write a result if there is one
      if(nrow(enriched.reactome) > 0){
        # paste the output path together
        enriched.reactome.loc <- paste(pathway.output.loc, comparison, '.tsv', sep = '')
        # write the result
        write.table(enriched.reactome, enriched.reactome.loc, sep = '\t', quote = T, row.names = F, col.names = T)
      }
      # now check for the positive genes
      de.output.positive <- de.output[de.output[[log.fc.column]] > 0, ]
      # check if there are any genes left
      if(nrow(de.output.positive) > 0){
        # grab the genes
        gene.symbols.sig.positive <- rownames(de.output.positive)
        # do the enrichment analysis
        enriched.positive <- enrichr(genes = gene.symbols.sig.positive, databases = c('Reactome_2016'))
        # grab the reactome result
        enriched.reactome.positive <- enriched.positive[['Reactome_2016']]
        # write a result if there is one
        if(nrow(enriched.reactome.positive) > 0){
          # paste the output path together
          enriched.reactome.positive.loc <- paste(pathway.output.loc, comparison, '_positive', '.tsv', sep = '')
          # write the result
          write.table(enriched.reactome.positive, enriched.reactome.positive.loc, sep = '\t', quote = T, row.names = F, col.names = T)
        }
      }
      # now check for the negative genes
      de.output.negative <- de.output[de.output[[log.fc.column]] < 0, ]
      # check if there are any genes left
      if(nrow(de.output.negative) > 0){
        # grab the genes
        gene.symbols.sig.negative <- rownames(de.output.negative)
        # do the enrichment analysis
        enriched.negative <- enrichr(genes = gene.symbols.sig.negative, databases = c('Reactome_2016'))
        # grab the reactome result
        enriched.reactome.negative <- enriched.negative[['Reactome_2016']]
        # write a result if there is one
        if(nrow(enriched.reactome.negative) > 0){
          # paste the output path together
          enriched.reactome.negative.loc <- paste(pathway.output.loc, comparison, '_negative', '.tsv', sep = '')
          # write the result
          write.table(enriched.reactome.negative, enriched.reactome.negative.loc, sep = '\t', quote = T, row.names = F, col.names = T)
        }
      }
    }
  }
}


```

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# Functions        #
####################

####################
# Main Code        #
####################

setEnrichrSite("Enrichr") # Human genes

# location of the Seurat MAST output
mast.output.meta.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/differential_expression/MAST/stemi_meta_paired_lores_lfc01minpct01ncountrna_20210301/rna/'
# location of the GSE output
gse.output.meta.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/pathway_enrichment/enrichr/MAST/stemi_meta_paired_lores_lfc01minpct01ncountrna_20210301/rna/'
# do the GSE
do_enrichr(mast.output.meta.loc, gse.output.meta.loc, p.val.column = 'metap_bonferroni', log.fc.column = 'metafc')


# for v2 as well
mast.output.v2.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/differential_expression/MAST/stemi_v2_paired_lores_lfc01minpct01ncountrna_20210301/rna/'
gse.output.v2.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/pathway_enrichment/enrichr/MAST/stemi_v2_paired_lores_lfc01minpct01ncountrna_20210301/rna/'
do_enrichr(mast.output.v2.loc, gse.output.v2.loc)

# and v3
mast.output.v3.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/differential_expression/MAST/stemi_v3_paired_lores_lfc01minpct01ncountrna_20210301/rna/'
gse.output.v3.loc <- '/groups/umcg-franke-scrna/tmp01/releases/blokland-2020/v1/pathway_enrichment/enrichr/MAST/stemi_v3_paired_lores_lfc01minpct01ncountrna_20210301/rna/'
do_enrichr(mast.output.v3.loc, gse.output.v3.loc)


```
