---
title: "stemi_plot_de_genes"
author: "Roy Oelen"
date: "2023-06-22"
output: html_document
---

```{r header, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#!/usr/bin/env Rscript
############################################################################################################################
# Authors: Roy Oelen
# Name: stemi_plot_de_genes.Rmd
# Function:
############################################################################################################################
```

```{r libraries, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
####################
# libraries        #
####################

library(ggplot2)
library(cowplot)

```

```{r functions, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
####################
# Functions        #
####################


get_color_coding_dict <- function(){
  # set the condition colors
  color_coding <- list()
  color_coding[["UTBaseline"]] <- "khaki2"
  color_coding[["UTt24h"]] <- "khaki4"
  color_coding[["UTt8w"]] <- "paleturquoise1"
  color_coding[["Baselinet24h"]] <- "paleturquoise3"
  color_coding[["Baselinet8w"]] <- "rosybrown1"
  color_coding[["t24ht8w"]] <- "rosybrown3"
  color_coding[["UT\nBaseline"]] <- "khaki2"
  color_coding[["UT\nt24h"]] <- "khaki4"
  color_coding[["UT\nt8w"]] <- "paleturquoise1"
  color_coding[["Baseline\nt24h"]] <- "paleturquoise3"
  color_coding[["Baseline\nt8w"]] <- "rosybrown1"
  color_coding[["t24h\nt8w"]] <- "rosybrown3"
  color_coding[["UT-Baseline"]] <- "khaki2"
  color_coding[["UT-t24h"]] <- "khaki4"
  color_coding[["UT-t8w"]] <- "paleturquoise1"
  color_coding[["Baseline-t24h"]] <- "paleturquoise3"
  color_coding[["Baseline-t8w"]] <- "rosybrown1"
  color_coding[["t24h-t8w"]] <- "rosybrown3"
  color_coding[["UT-t0"]] <- "khaki2"
  color_coding[["UT-t24h"]] <- "khaki4"
  color_coding[["UT-t8w"]] <- "paleturquoise1"
  color_coding[["HC-t0"]] <- "khaki2"
  color_coding[["HC-t24h"]] <- "khaki4"
  color_coding[["HC-t8w"]] <- "paleturquoise1"
  color_coding[["t0-t24h"]] <- "paleturquoise3"
  color_coding[["t0-t8w"]] <- "rosybrown1"
  color_coding[["t24h-t8w"]] <- "rosybrown3"
  # set condition colors
  color_coding[["HC"]] <- "grey"
  color_coding[["Control"]] <- "grey"
  color_coding[["C"]] <- "grey"
  color_coding[["t0"]] <- "#ff7101"
  color_coding[["t24h"]] <- "#e12a62"
  color_coding[["t8w"]] <- "#3B0550"
  color_coding[["t6-8w"]] <- "#3B0550"
  # set the cell type colors
  color_coding[["Bulk"]] <- "black"
  color_coding[["CD4T"]] <- "#153057"
  color_coding[["CD8T"]] <- "#009DDB"
  color_coding[["monocyte"]] <- "#EDBA1B"
  color_coding[["NK"]] <- "#E64B50"
  color_coding[["B"]] <- "#71BC4B"
  color_coding[["DC"]] <- "#965EC8"
  color_coding[["CD4+ T"]] <- "#153057"
  color_coding[["CD8+ T"]] <- "#009DDB"
  # other cell type colors
  color_coding[["HSPC"]] <- "#009E94"
  color_coding[["platelet"]] <- "#9E1C00"
  color_coding[["plasmablast"]] <- "#DB8E00"
  color_coding[["other T"]] <- "#FF63B6"
  return(color_coding)
}

label_dict <- function(){
  label_dict <- list()
  # condition combinations
  label_dict[['UTBaseline']] <- 'UT-Baseline'
  label_dict[['UTt24h']] <- 'UT-t24h'
  label_dict[['UTt8w']] <- 'UT-t8w'
  label_dict[['Baselinet24h']] <- 'Baseline-t24h'
  label_dict[['Baselinet8w']] <- 'Baseline-t8w'
  label_dict[['t24ht8w']] <- 't24h-t8w'
  label_dict[['UTBaseline']] <- 'HC-t0'
  label_dict[['UTt24h']] <- 'HC-t24h'
  label_dict[['UTt8w']] <- 'HC-t8w'
  label_dict[['Baselinet24h']] <- 't0-t24h'
  label_dict[['Baselinet8w']] <- 't0-t8w'
  # conditions
  label_dict[['UT']] <- 'Control'
  label_dict[['Baseline']] <- 't0'
  label_dict[['t24h']] <- 't24h'
  label_dict[['t8w']] <- 't6-8w'
  label_dict[['C']] <- 'C'
  label_dict[['Control']] <- 'Control'
  label_dict[['t0']] <- 't0'
  label_dict[['t24h']] <- 't24h'
  label_dict[['t6w']] <- 't6-8w'
  label_dict[['t8w']] <- 't6-8w'
  # major cell types
  label_dict[["Bulk"]] <- "bulk-like"
  label_dict[["CD4T"]] <- "CD4+ T"
  label_dict[["CD8T"]] <- "CD8+ T"
  label_dict[["monocyte"]] <- "monocyte"
  label_dict[["NK"]] <- "NK"
  label_dict[["B"]] <- "B"
  label_dict[["DC"]] <- "DC"
  label_dict[["HSPC"]] <- "HSPC"
  label_dict[["plasmablast"]] <- "plasmablast"
  label_dict[["platelet"]] <- "platelet"
  label_dict[["T_other"]] <- "other T"
  # minor cell types
  label_dict[["CD4_TCM"]] <- "CD4 TCM"
  label_dict[["Treg"]] <- "T regulatory"
  label_dict[["CD4_Naive"]] <- "CD4 naive"
  label_dict[["CD4_CTL"]] <- "CD4 CTL"
  label_dict[["CD8_TEM"]] <- "CD8 TEM"
  label_dict[["cMono"]] <- "cMono"
  label_dict[["CD8_TCM"]] <- "CD8 TCM"
  label_dict[["ncMono"]] <- "ncMono"
  label_dict[["cDC2"]] <- "cDC2"
  label_dict[["B_intermediate"]] <- "B intermediate"
  label_dict[["NKdim"]] <- "NK dim"
  label_dict[["pDC"]] <- "pDC"
  label_dict[["ASDC"]] <- "ASDC"
  label_dict[["CD8_Naive"]] <- "CD8 naive"
  label_dict[["MAIT"]] <- "MAIT"
  label_dict[["CD8_Proliferating"]] <- "CD8 proliferating"
  label_dict[["CD4_TEM"]] <- "CD4 TEM"
  label_dict[["B_memory"]] <- "B memory"
  label_dict[["NKbright"]] <- "NK bright"
  label_dict[["B_naive"]] <- "B naive"
  label_dict[["gdT"]] <- "gamma delta T"
  label_dict[["CD4_Proliferating"]] <- "CD4 proliferating"
  label_dict[["NK_Proliferating"]] <- "NK proliferating"
  label_dict[["cDC1"]] <- "cDC1"
  label_dict[["ILC"]] <- "ILC"
  label_dict[["dnT"]] <- "double negative T"
  return(label_dict)
}


get_significant_genes <- function(mast_output_loc, pval_column='metap_bonferroni', sig_pval=0.05, max=NULL, max_by_pval=T, only_positive=F, only_negative=F, lfc_column='metafc', to_ens=F, symbols.to.ensg.mapping='genes.tsv'){
  # get the files
  files <- list.files(mast_output_loc)
  # store the results
  results_per_file <- list()
  # try to read each file
  for(file in files){
    try({
      # read the mast output
      mast <- read.table(paste(mast_output_loc, file, sep = ''), header=T)
      # filter to only include the significant results
      mast <- mast[mast[[pval_column]] <= sig_pval, ]
      # filter for only the positive lfc if required
      if(only_positive){
        mast <- mast[mast[[lfc_column]] < 0, ]
      }
      # filter for only the positive lfc if required
      if(only_negative){
        mast <- mast[mast[[lfc_column]] > 0, ]
      }
      # confine in some way if reporting a max number of genes
      if(!is.null(max)){
        # by p if required
        if(max_by_pval){
          mast <- mast[order(mast[[p_val_column]]), ]
        }
        # by lfc otherwise
        else{
          mast <- mast[order(mast[[lfc_column]], decreasing = T), ]
        }
        # subset to the number we requested if max was set
        mast <- mast[1:max,]
      }
      # grab the genes from the column names
      genes <- rownames(mast)
      # convert the symbols to ensemble IDs
      if (to_ens) {
        mapping <- read.table(symbols.to.ensg.mapping, header = F, stringsAsFactors = F)
        mapping$V2 <- gsub("_", "-", make.unique(mapping$V2))
        genes <- mapping[match(genes, mapping$V2),"V1"]
      }
      # otherwise change the Seurat replacement back
      else{
        #genes <- gsub("-", "_", genes)
      }
      # create a regex to get the last index of .
      last_dot_pos <- "\\.[^\\.]*$"
      # this allows us to remove the filename extention
      file_no_ext <- substr(file, 1, regexpr(last_dot_pos,file)-1)
      # put the result in the list
      results_per_file[[file_no_ext]] <- mast
    })
  }
  return(results_per_file)
}


get_max_lfc_genes <- function(output_per_comparison, pval_column='metap_bonferroni', sig_pval=0.05, max=5, only_positive=F, only_negative=F, lfc_column='metafc') {
  # create a list per key
  genes_per_entry <- list()
  # check each output
  for (output_name in names(output_per_comparison)) {
    mast <- output_per_comparison[[output_name]]
    # filter to only include the significant results
    mast <- mast[mast[[pval_column]] <= sig_pval, ]
    # filter for only the positive lfc if required
    if(only_positive){
      mast <- mast[mast[[lfc_column]] < 0, ]
    }
    # filter for only the positive lfc if required
    if(only_negative){
      mast <- mast[mast[[lfc_column]] > 0, ]
    }
    # order by lfc
    mast <- mast[order(abs(mast[[lfc_column]]), decreasing = T), ]
    # subset to the top whatever
    max_num <- max
    if (max_num > nrow(mast)) {
      max_num <- nrow(mast)
    }
    mast <- mast[1:max_num,]
    # put those in the resulting list
    genes_per_entry[[output_name]] <- rownames(mast)
  }
  return(genes_per_entry)
}


merge_genes_into_table <- function(output_per_comparison, max_genes_per_comparison, merge_groups) {
  # get the names present in both lists
  comparisons <- intersect(names(output_per_comparison), names(max_genes_per_comparison))
  # put the results in a list first, which we will merge later
  filtered_comparison_results_list <- list()
  # check each group
  for (merge_group in names(merge_groups)) {
    # get the comparisons that are in this group
    comparisons <- merge_groups[[merge_group]]
    # create a joined vector for the genes in this group
    genes_group <- c()
    # check each comparison
    for (comparison in comparisons) {
      # get the genes we are interested in
      genes <- max_genes_per_comparison[[comparison]]
      # remove any empty entries that might be there
      genes <- genes[!is.na(genes)]
      # add to the genes group
      genes_group <- c(genes_group, genes)
    }
    # now that we have the genes, we can get all the genes
    for (comparison in comparisons) {
      # get the table that has these genes
      results_comparison <- output_per_comparison[[comparison]]
      # we might not have tested all genes, so we need to take that into consideration
      genes_to_subset <- intersect(genes_group, rownames(results_comparison))
      # if we have any left, we can subset our result
      if (length(genes_to_subset) > 0 ) {
        # subset to those genes
        results_comparison <- results_comparison[genes_to_subset, ]
        # add a column that denotes the comparison
        results_comparison <- cbind(data.frame(comparison = rep(comparison, times = length(genes_to_subset)), gene = genes_to_subset),
                                  results_comparison)
        # put that in the list
        filtered_comparison_results_list[[comparison]] <- results_comparison
      }
    }
  }
  # merge the list of tables
  filtered_comparison_results <- do.call('rbind', filtered_comparison_results_list)
  return(filtered_comparison_results)
}


lfc_table_to_tile <- function(lfc_table, gene_column='gene', comparison_column='vs_timepoint', value_column='avg_lfc', use_label_mapping=T, paper_style=T, print_lfc_value=T, round_digits=2, align_right=T, legendless=F, colour_ticks=F, x_order=NULL, y_order=NULL) {
  # change the celltype label if requested
  if (use_label_mapping) {
    lfc_table[[comparison_column]] <- as.vector(unlist(label_dict()[as.character(lfc_table[[comparison_column]])]))
  }
  # order the gene names by alphabet
  genes <- unique(lfc_table[[gene_column]])
  genes_reverse_alphabet <- genes[order(genes, decreasing = T)]
  lfc_table[[gene_column]] <- as.factor(lfc_table[[gene_column]])
  lfc_table[[gene_column]] <- factor(lfc_table[[gene_column]], levels = genes_reverse_alphabet)
  # extract the maximum absolute value
  max_abs_lfc <- max(abs(lfc_table[[value_column]]))
  # set the x labels as factors, but first backup the string representation
  comparisons <- unique(lfc_table[[comparison_column]])
  lfc_table[[comparison_column]] <- as.factor(lfc_table[[comparison_column]])
  # and order them
  if (!is.null(x_order)) {
    lfc_table[[comparison_column]] <- factor(lfc_table[[comparison_column]], levels = x_order)
  }
  else {
    lfc_table[[comparison_column]] <- factor(lfc_table[[comparison_column]], levels = comparisons[order(comparisons)])
  }
  # same for y order
  genes <- unique(lfc_table[[gene_column]])
  if (!is.null(y_order)) {
    lfc_table[[gene_column]] <- factor(lfc_table[[gene_column]], levels = y_order)
  }
  else{
    lfc_table[[gene_column]] <- factor(lfc_table[[gene_column]], levels = genes[order(genes)])
  }
  # make the plot
  p <- ggplot(data = NULL, aes(x = lfc_table[[comparison_column]], y = lfc_table[[gene_column]], fill = lfc_table[[value_column]])) + geom_tile() + coord_equal()
  # set the gradient equally from zero in both directions
  p <- p + scale_fill_gradientn(colours = c('blue', 'white', 'red'),  limits = (c(-1 * max_abs_lfc, max_abs_lfc)), name = 'Average\nLFC')
  # add the values of the LFC if requested
  if (print_lfc_value) {
    p <- p + geom_text(aes(label = round(lfc_table[[value_column]], digits = round_digits)), size=2)
  }
  # align to the right side
  if (align_right) {
    p <- p + scale_y_discrete(position = 'right')
  }
  # and labels
  p <- p + xlab(comparison_column) + ylab(gene_column)
  # paper style if requested
  if (paper_style) {
    p <- p + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), strip.background = element_rect(colour="white", fill="white"))
  }
  # remove legend if requested
  if(legendless){
    p <- p + theme(legend.position = 'none')
  }
  # rotate labels
  p <- p + theme(axis.text.x = element_text(angle = 90))
  # colour the ticks if requested
  if (colour_ticks) {
    # get the labels
    x_labels <- levels(lfc_table[[comparison_column]])
    # get the appropriate colours
    x_colours <- as.vector(unlist(get_color_coding_dict()[as.character(x_labels)]))
    p <- p + theme(axis.ticks = element_line(),      # Change ticks line fo all axes
    axis.ticks.x = element_line(linewidth = 7, colour = x_colours),    # Change x axis ticks only
    )
  }
  return(p)
}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
####################
# Main Code        #
####################

mast_meta_output_loc_lfc01 <- '/groups/umcg-franke-scrna/tmp02/releases/blokland-2020/v1/differential_expression/MAST/stemi_meta_paired_lores_lfc01minpct01ncountrna_20210301/rna/'

```

```{r setup, include=TRUE, fig.width=8, fig.height=8}

# get the output
output_per_comparison_up <- get_significant_genes(mast_meta_output_loc_lfc01, sig_pval = 1, only_positive = T)
output_per_comparison_down <- get_significant_genes(mast_meta_output_loc_lfc01, sig_pval = 1, only_positive = T)

# and the top genes
genes_per_comparison_up <- max_genes_per_comparison_up <- get_max_lfc_genes(output_per_comparison_up, max = 10)
genes_per_comparison_down <- max_genes_per_comparison_down <- get_max_lfc_genes(output_per_comparison_down, max = 10)
# create merging groups
merge_groups <- list(
  'monocyte' = c('monocyteUTBaseline', 'monocyteBaselinet24h', 'monocyteBaselinet8w')
)
# get the LFCs for those genes
output_specific_genes_up <- merge_genes_into_table(output_per_comparison_up, genes_per_comparison_up, merge_groups)
# make a table specific for the monocytes, with all comparisons agains monocytes
mono_table <- rbind(data.frame(vs_timepoint = 't24h', gene = output_specific_genes_up[output_specific_genes_up[['comparison']] == 'monocyteBaselinet24h', 'gene'], avg_lfc=-1*output_specific_genes_up[output_specific_genes_up[['comparison']] == 'monocyteBaselinet24h', 'metafc']),
                    data.frame(vs_timepoint = 't8w', gene = output_specific_genes_up[output_specific_genes_up[['comparison']] == 'monocyteBaselinet8w', 'gene'], avg_lfc=-1*output_specific_genes_up[output_specific_genes_up[['comparison']] == 'monocyteBaselinet8w', 'metafc']),
                    data.frame(vs_timepoint = 'C', gene = output_specific_genes_up[output_specific_genes_up[['comparison']] == 'monocyteUTBaseline', 'gene'], avg_lfc=1*output_specific_genes_up[output_specific_genes_up[['comparison']] == 'monocyteUTBaseline', 'metafc']))

# set the order we want to display at
mono_x_order <- c('t24h', 't6-8w', 'C')
# set the y order
mono_y_order <- unique(mono_table[order(mono_table[['avg_lfc']]), 'gene'])
# create a picture
lfc_table_to_tile(mono_table, print_lfc_value = T, colour_ticks = T, x_order = mono_x_order, y_order = mono_y_order) + ggtitle('Monocytes') + ylab('Gene symbol') + xlab('Timepoint compared')

```

```{r setup, include=TRUE, fig.width=8, fig.height=8}

# get the output
output_per_comparison_up <- get_significant_genes(mast_meta_output_loc_lfc01, sig_pval = 1, only_positive = T)
output_per_comparison_down <- get_significant_genes(mast_meta_output_loc_lfc01, sig_pval = 1, only_positive = T)

# and the top genes
genes_per_comparison_up <- max_genes_per_comparison_up <- get_max_lfc_genes(output_per_comparison_up, max = 10)
genes_per_comparison_down <- max_genes_per_comparison_down <- get_max_lfc_genes(output_per_comparison_down, max = 10)
# create merging groups
merge_groups <- list(
  'NK' = c('NKUTBaseline', 'NKBaselinet24h', 'NKBaselinet8w')
)
# get the LFCs for those genes
output_specific_genes_up <- merge_genes_into_table(output_per_comparison_up, genes_per_comparison_up, merge_groups)
# make a table specific for the NKs, with all comparisons agains NKs
NK_table <- rbind(data.frame(vs_timepoint = 't24h', gene = output_specific_genes_up[output_specific_genes_up[['comparison']] == 'NKBaselinet24h', 'gene'], avg_lfc=-1*output_specific_genes_up[output_specific_genes_up[['comparison']] == 'NKBaselinet24h', 'metafc']),
                    data.frame(vs_timepoint = 't8w', gene = output_specific_genes_up[output_specific_genes_up[['comparison']] == 'NKBaselinet8w', 'gene'], avg_lfc=-1*output_specific_genes_up[output_specific_genes_up[['comparison']] == 'NKBaselinet8w', 'metafc']),
                    data.frame(vs_timepoint = 'C', gene = output_specific_genes_up[output_specific_genes_up[['comparison']] == 'NKUTBaseline', 'gene'], avg_lfc=1*output_specific_genes_up[output_specific_genes_up[['comparison']] == 'NKUTBaseline', 'metafc']))

# remove LFC below 0.1, as we did not test it
NK_table <- NK_table[NK_table[['avg_lfc']] > 0.1 | NK_table[['avg_lfc']] < -0.1, ]

# set the order we want to display at
NK_x_order <- c('t24h', 't6-8w', 'C')
# set the y order
NK_y_order <- unique(NK_table[order(NK_table[['avg_lfc']]), 'gene'])
# create a picture
lfc_table_to_tile(NK_table, print_lfc_value = T, colour_ticks = T, x_order = NK_x_order, y_order = NK_y_order) + ggtitle('NKs') + ylab('Gene symbol') + xlab('Timepoint compared')

```